### ISSUE TITLE
Possible typo in id

### ISSUE THREAD

**Issue by infidel** [wmo-im/iwxxm-translation#2]
https://github.com/wmo-im/iwxxm-translation/blob/936e771310bb0d52d3dde31db70221873fe22312/Amd77-2016/sigmet/sigmet-A6-2-TC.xml#L36

Should it be gml:id="mwo-YUDO" instead of gml:id="wmo-YUDO", similar to the UnitTimeSlice?

**Comment by infidel** [comment]
Is this repo still in use. I see now that the same files are in the main one https://github.com/wmo-im/iwxxm/blob/master/2.1.1/examples/sigmet-A6-2-TC.xml#L37

**Comment by blchoy** [comment]
Thanks for pointing out.  I think MWO (Meteorological Watch Office) is the one intended to be used in the example but this is not a must.  There are some descriptions of the choice of gml:id at the bottom of https://wiswiki.wmo.int/tiki-index.php?page=IWXXM-Tutorial-collect.  Up to IWXXM 2.1.1 there are no requirements on the choice of gml:id except that they have to be unique even after being included in different bulletins.  In IWXXM 3 we will mandate the use of UUIDs in gml:ids.  See #31 for details.
